name: Deploy Preview

on:
  pull_request:
    branches:
      - master # Change to your default branch if it's not 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18' # Use your required Node.js version

      - name: Install dependencies
        run: yarn install

      - name: Build the project
        run: yarn build

      - name: Deploy to Surge
        env:
          PROJECT_NAME: ${{ secrets.SURGE_PROJECT_NAME }}-${{ github.event.number }} # Construct project name with PR number
        run: |
          yarn global add surge  # Install Surge CLI in the GitHub Actions environment
          surge --project ./dist --domain $PROJECT_NAME.surge.sh --token ${{ secrets.SURGE_TOKEN }}

      - name: Comment on PR with live URL
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.DANGER_GITHUB_API_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments \
          -d '{"body": "Preview deployed at: https://'"${{ secrets.SURGE_PROJECT_NAME }}-${{ github.event.number }}".surge.sh"'. Visit the link for a live preview."}'
