name: Deploy Vercel PR Preview (Team)

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install # or npm install

      - name: Deploy to Vercel (Team)
        run: |
          curl -X POST https://api.vercel.com/v13/deployments \
          -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
            "name": "your-project-name",
            "project": "${{ secrets.VERCEL_PROJECT_ID }}",
            "teamId": "${{ secrets.VERCEL_TEAM_ID }}",
            "gitSource": {
              "org": "your-github-org",
              "repo": "your-repo-name",
              "pr": "'${{ github.event.number }}'"
            }
          }'

      - name: Output Vercel Deployment URL
        run: echo "PR deployed to Vercel"
